### ISSUE TITLE
Serializationgroup Support

### ISSUE THREAD

**Issue by GrmpfNarf** [Elao/PhpEnums#106]
Hello everyone,
is there any need for the support of ``Symfony\Component\Serializer\Annotation\Groups`` for an enum ?
With this it is possible to reduce or expand the enum based on the (de)serializationgroup.

I have already implemented this feature and will be able to provide a PR if there is a need for this feature.

**Comment by ogizanagi** [comment]
Hi @GrmpfNarf 

>  reduce or expand the enum based

What do you mean exactly?

**Comment by GrmpfNarf** [comment]
Hi,
in our case it is necessary to reduce the possible values of an enum in the Open Api documentation (and of course in the normalizer) by the given serializationgroups.

An example:

```php
<?php

namespace App\Enum;

use Elao\Enum\AutoDiscoveredValuesTrait;
use Elao\Enum\Enum;

class ActionEnum extends Enum
{
    use AutoDiscoveredValuesTrait;

    public const ADD = 'ADD';

    public const MODIFY = 'MODIFY';

    public const DELETE = 'DELETE';
}
```

In one Api Platform endpoint all enum values are possible and in another one just a subset.
But the entity which is used should stay the same, and creating a DTO just to change the allowed enum values seems a litte bit overdressed.

So I want to use serializationgroups to reduce the possible enum values in this endpoint:

```php
<?php

namespace App\Enum;

use Elao\Enum\AutoDiscoveredValuesTrait;
use Elao\Enum\Enum;
use Symfony\Component\Serializer\Annotation\Groups;

class ActionEnum extends Enum
{
    use AutoDiscoveredValuesTrait;

    /**
     * @Groups({"full", "partially"})
     */
    public const ADD = 'ADD';

    /**
     * @Groups({"full", "partially"})
     */
    public const MODIFY = 'MODIFY';

    /**
     * @Groups({"full"})
     */
    public const DELETE = 'DELETE';
}
```


Now the API platform has two models one
``Model-full`` and one
``Model-partially``

When I look at the schema in the Open Api documentation die ``Model-full`` looks like this:

```yaml
someProperty:
          type: string
          enum:
            - ADD
            - MODIFY
            - DELETE
          example: ADD
```

The model of ``Model-partially`` looks like this:

```yaml
someProperty:
          type: string
          enum:
            - ADD
            - MODIFY
          example: ADD
```

And in the denormalization process an ``UnexpectedValueException`` is thrown when I try to set ``DELETE`` on a endpoint which don't have the group ``full``.
