### ISSUE TITLE
Nullability support for API platform swagger documentation

### ISSUE THREAD

**Issue by rcoiffard** [Elao/PhpEnums#138]
We noticed that the ElaoEnumType-Factory does not pupose the `null` value for "nullable" fields in the json-schema documentation (swagger).

The swagger specifications indicate that a nullable enumeration can be defined as follows: (https://swagger.io/docs/specification/data-models/enums/)
```yaml
type: string
nullable: true  # <---
enum:
  - asc
  - desc
  - null        # <--- without quotes, i.e. null not "null"
```

Currently, API Platform responds with this (which is a problem for some swagger validators):
```yaml
type: string
nullable: true  # <---
enum:
  - asc
  - desc
```
